config/routes.rb
Rails.application.routes.draw do

  resources :products
  
  resources :cart, only:[:show]
  
  resources :contacts
  
  resources :users
  
  resources :order_items, only: [:create,:update,:destroy]
  
  resources :reviews

  get 'order_items/create'
  get 'aaa' => 'order_items#new'
  get 'order_items/update'
  get 'order_items/destroy'
  get 'createOrderItem' => 'products#createOrderItem'

  get 'womens' => 'products#women'
  get 'mens' => 'products#men'
  get 'sport' => 'products#sport'
  get 'subcategory' => 'products#subcategory'
  get 'priceRange' => 'products#priceRange'
  get 'search' => 'products#search'
  get 'products/index'
  
  get 'contact' => 'contacts#new'
  get 'contacts/new'
  
  get 'home' => 'site#home'
  get 'about' => 'site#about'

  get 'change_details' => 'users#change_details'
  get 'updateAccount' => 'users#updateAccount'
  get 'updateBilling' => 'users#updateBilling'
  get 'updateDelivery' => 'users#updateDelivery'
  get 'account' => 'users#show'
  
  get 'login'   => 'sessions#new'
  post 'login'   => 'sessions#create'
  get 'logout'  => 'sessions#destroy'
  get 'loginerror' => 'sessions#error'
  
  get 'cartcreate' => 'carts#create'
  get 'cart' => 'carts#index'
  get 'checkout' => 'carts#checkout'
  get 'submitOrder' => 'carts#submitOrder'
  get 'viewcart' => 'carts#view'
  
  get 'ordersignoff' => 'admin#ordersignoff'
  get 'viewmessages' => 'admin#viewmessages'
  get 'viewproducts' => 'admin#viewproducts'
  get 'editproduct' => 'admin#editproduct'
  
  
  root 'site#home'

end

app/models/product.rb
class Product < ActiveRecord::Base
  has_many :reviews
  has_many :order_items
  
  
  #THIS MIGHT HAVE TO GO IF WE HAVE NOT SETUP THE COLUMN ACTIVE IN PRODUCT
  #IT WENT :)
  #default_scope {where(active:true)}
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  #When the index controller is called it stores all the products in a Products and Orders in Order_Items
  def index
    #@TempOrder=OrderItem.new
  end
  

  
  def show
    #Adding to the final ID that is returned as this will be the new ID
    #@temp_order_id= "TEST VALUE TO SEE"
    #Select id from Order ORDER BY 
    @product = Product.find(params[:id])
    @recommended = Product.where(subcategory: @product.subcategory).shuffle.take(4)
    @reviews = Review.where(Product_id: params[:id])
    @TempOrder = OrderItem.new
    @TempProductID=Order.last
    #@total_price=OrderItem.select('Total_Price').where(:OrderId => '0').sum(:Total_Price)
   
  end
  
  def new
    #@item = Item.new
  end
  
  def edit
  end
  
  def men
    #This is the search that does a search with a where clause
    @products = Product.where(Catagory:"men").shuffle
    @category = 'men'
    @subcategory = 'none'
    #This redirects to the view
    render 'products/index'
  end
  
  def women
    #This is the search that does a search with a where clause
    @products = Product.where(Catagory:"women").shuffle
    @category = 'women'
    @subcategory = 'none'
    #This redirects to the view
    render 'products/index'
    
  end
  
  def sport
    #This is the search that does a search with a where clause
    @products = Product.where("Catagory = 'sport' AND subcategory <> 'equipment'").shuffle
    @category = 'sport'
    @subcategory = 'none'
    #This redirects to the view
    render 'products/index'
  end
  
  def subcategory
    @products = Product.where(subcategory: params[:subcategory]).shuffle
    @subcategory = params[:subcategory]
    @category = params[:breadcrumbsCategory]
    render 'products/index'
  end
  
  def priceRange
    subcat = params[:subcategory]
    if params[:subcategory].eql? "none"
      subcat = "%"
    end  
    
    max = params[:max]
    if max.eql? "none"
      max = "%"
    end
    
    @products = Product.where("price BETWEEN ? AND ? AND Catagory = ? AND subcategory LIKE ?", params[:min], max, params[:breadcrumbsCategory], subcat)
    @subcategory = params[:subcategory]
    @category = params[:breadcrumbsCategory]
    render 'products/index'
  end
  
  def search
    @products = Product.where("title like '%#{params[:searchbar]}%' AND Catagory = '#{params[:breadcrumbsCategory]}' ")
    @category = params[:breadcrumbsCategory]
    @subcategory = params[:subcategory]
    render 'products/index'
  end
  
  private
    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      # Add more permits here
      params.require(:product).permit(:id, :title, :description, :price, :features, :catagory, :subcategory, :color)
      params.require(:review).permit(:id, :Comment, :userId, :Rating, :product_id, :Date)
    end
    
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_product.html.erb
<%= link_to image_tag(product.image_url, :class => "productsimg"), product %>

<h3 class="title"><%= link_to product.Title, product %></h3>

<div class="functionality">
<div class="productrating<%= index %>" style="width: 61%; float: left;"></div>
<div class="price"><%= number_with_precision(product.price, precision: 2) %></div>
</div>
<script>
$('.productrating<%= index %>').raty({
    readOnly: true,
    hints: ['Abominable', 'Poor', 'Average', 'Good', 'Gorgeous'],
    score: <%= product.rating %>,
    path: '/assets/products'
  });
</script>

app/views/products/_review.html.erb
<div id="reviewRatingStars<%= index %>" style="width: 20%; float: left;"></div>
<div id="reviewSummary">
  <%= review.summary %>
</div>
<div id="reviewDate">
  <%= review.Date.strftime("%Y-%b-%d") %>
</div>
<div id="reviewBy">
  <div style="font-family: 'Cabin', Helvetica, Arial, sans-serif; width: 20px; float: left;">By</div>
  <% user = User.find_by(id: review.userId) %>
  <%= user.name + " " + user.lastname %>
</div>
<div id="reviewComment">
  <%= review.Comment %>
</div>

<script>
$('#reviewRatingStars<%= index %>').raty({
    readOnly: true,
    space: false,
    hints: ['Abominable', 'Poor', 'Average', 'Good', 'Gorgeous'],
    score: <%= review.Rating %>,
    path: '/assets/products'
  });
</script>

app/views/products/index.html.erb
<% content_for :title do %>
Shopping @ IN Fashion
<% end %>

<% content_for :header do%>
<div id="search">
 <%= form_tag "search", method: "get", :class => "form" do %>
  <%= text_field_tag(:searchbar) %>
  <%= hidden_field_tag :breadcrumbsCategory, @category %>
  <%= hidden_field_tag :subcategory, 'none' %>
  <%= submit_tag "Go", :class => "formsubmit", :style => "margin-bottom: 0px;" %> 
<% end %>
</div>
<% end %>

<% content_for :content do %>
<div id="refine">
 <h3>Refine Results</h3>
 
 <div id="refinecont">
  <div id="sub">
  <h4>Subcategory</h4>
   <ul>
    <% if @category.eql? 'women' %>
     <li>
      <%= link_to "Skirts & Dresses", :action => 'subcategory', :subcategory => 'dress', :breadcrumbsCategory => @category %>
     </li>
     <li>
      <%= link_to "Business Attire", :action => 'subcategory', :subcategory => 'business', :breadcrumbsCategory => @category %>
     </li>
     <li>
      <%= link_to "Casual", :action => 'subcategory', :subcategory => 'casual-Women', :breadcrumbsCategory => @category %>
     </li>
     <li>
      <%= link_to "Jumpers and Coats", :action => 'subcategory', :subcategory => 'coats-Women', :breadcrumbsCategory => @category %>
     </li>
     <li>
     <%= link_to "Shoes", :action => 'subcategory', :subcategory => 'shoes-Women', :breadcrumbsCategory => @category %>
    </li>
    <li>
     <%= link_to "Accessories", :action => 'subcategory', :subcategory => 'accessories-Women', :breadcrumbsCategory => @category %>
    </li>
     <% end %>

    <% if @category.eql? 'men' %>
     <li>
      <%= link_to "Suits", :action => 'subcategory', :subcategory => 'suits', :breadcrumbsCategory => @category %>
     </li>
     <li>
      <%= link_to "Casual", :action => 'subcategory', :subcategory => 'casual-Men', :breadcrumbsCategory => @category %>
     </li>
     <li>
      <%= link_to "Jumpers and Coat", :action => 'subcategory', :subcategory => 'coats-Men', :breadcrumbsCategory => @category %>
     </li>
     <li>
     <%= link_to "Shoes", :action => 'subcategory', :subcategory => 'shoes-Men', :breadcrumbsCategory => @category %>
    </li>
    <li>
     <%= link_to "Accessories", :action => 'subcategory', :subcategory => 'accessories-Men', :breadcrumbsCategory => @category %>
    </li>
    <% end %>
    
    <% if @category.eql? 'sport' %>
     <li>
      <%= link_to "Women's Sport Gear", :action => 'subcategory', :subcategory => 'gear-Women', :breadcrumbsCategory => @category %>
     </li>
     <li>
      <%= link_to "Men's Sport Gear", :action => 'subcategory', :subcategory => 'gear-Men', :breadcrumbsCategory => @category %>
     </li>
     <li>
      <%= link_to "Women's Shoes", :action => 'subcategory', :subcategory => 'sport-Shoes-Women', :breadcrumbsCategory => @category %>
     </li>
     <li>
      <%= link_to "Men's Shoes", :action => 'subcategory', :subcategory => 'sport-Shoes-Men', :breadcrumbsCategory => @category %>
     </li>
      <li>
      <%= link_to "Workout Equipment", :action => 'subcategory', :subcategory => 'equipment', :breadcrumbsCategory => @category %>
     </li>
    <% end %>
  
   </ul>
  </div>
  
  <div id="pri">
   <h4>Price Range</h4>
   <ul>
    <li>
     <%= link_to "€0 - €30", :action => 'priceRange', :subcategory => @subcategory, :breadcrumbsCategory => @category, :min => 0, :max => 30 %>
    </li>
    <li>
     <%= link_to "€30 - €70", :action => 'priceRange', :subcategory => @subcategory, :breadcrumbsCategory => @category, :min => 30, :max => 70 %>
    </li>
    <li>
     <%= link_to "€70 - €150", :action => 'priceRange', :subcategory => @subcategory, :breadcrumbsCategory => @category, :min => 70, :max => 150 %>
    </li>
    <li>
     <%= link_to "€150 - €300", :action => 'priceRange', :subcategory => @subcategory, :breadcrumbsCategory => @category, :min => 150, :max => 300 %>
    </li>
    <li>
     <%= link_to "300+", :action => 'priceRange', :subcategory => @subcategory, :breadcrumbsCategory => @category, :min => 300, :max => "none" %>
    </li>
   </ul>
  </div>
 </div>
</div>
 
<div id="products">
 <div id="breadcrumbs" style="padding-top: 1%; padding-left: 1%;">
  <ul>
    <li>
      <h4><%= link_to "Home", :action => 'home', :controller => :site %></h4>
    </li>
    <li>
      >
    </li>
    <li>
      <h4><%= link_to @category.titlecase, :action => @category, :breadcrumbsCategory => @category %></h4>
    </li>
    <li>
      >
    </li>
    <% if @subcategory != 'none' %>
    <li>
      <h4>
       <%= link_to @subcategory.titlecase, :action => 'subcategory', 
       :subcategory => @subcategory, :breadcrumbsCategory => @category %>
      </h4>
    </li>
    <li>
      >
    </li>
    <% end %>
  </ul>
 </div>
 <table id="productsTable">
  <col width="23%" />
  <col width="23%" />
  <col width="23%" />
  <col width="23%" />
 <% @products.each_with_index do |product, index| %>
  <% if index % 4 == 0 %>
   <tr>
  <% end %>
   <td>
    <div class="eachproduct">
      <%= render partial: "product", locals: {product: product, index: index} %>
    </div>
   </td>
   <% if index % 4 == 3 %>
    </tr>
   <% end %>
  <% end %>
  <!-- Extra td have to be added to correct table spacing to four in a row, aesthetic hacking -->
  <% if @products.length < 4 %>
    <td>
    </td>
    <% if @products.length < 3 %>
     <td>
     </td>
     <% if @products.length < 2 %>
      <td>
      </td>
     <% end %>
    <% end %>
   <% end %>
  </table>
  <% if @products.length == 0 && params[:searchbar] != nil %>
   <p ckass="nomatches">Sorry, no matches found for: "<%= params[:searchbar] %>"</p>
  <% elsif @products.length == 0 %>
   <p class="nomatches">Sorry, no matches found in this price range</p>
  <% end %>
 </div>

<% end %>

app/views/products/item.html.erb
<% content_for :header do %>
<div id="search">
 <form>
  <input id="searchbar" type="search" name="productsearch" placeholder="Search Products..." />
 </form>
</div>
<% end %>

<% content_for :content do %>
<div id="itemcont">
<div id="breadcrumbs">
  <ul>
    <li>
      <h4><a href="home">Home</a></h4>
    </li>
    <li>
      >
    </li>
    <li>
      <h4><a href="#">e.g Womens</a></h4>
    </li>
    <li>
      >
    </li>
    <li>
      <h4><a href="#">e.g. Gloves</a></h4>
    </li>
    <li>
      >
    </li>
  </ul>
</div>

<div id="item">
  
  <h2>Item Title</h2>
  
  <div id="itemimg">
    <img src="assets/site/header.jpg" alt="Product Image" />
  </div>
  
  <div id="itemdesc">
    <h4 id="itemprice">Price here</h4>
    
    <div id="rating">
      <span>☆</span>
      <span>☆</span>
      <span>☆</span>
      <span>☆</span>
      <span>☆</span>
      <br/>
      <ul id="review">
        <li>
          <h4><a href="#">View Reviews</a></h4> 
        </li>
        <li>
          ||
        </li>
        <li>
          <h4><a href="#">Review this Product</a></h4>
        </li>
      </ul>
    </div>

    <div id="desc">
      In ex sapien, pellentesque ut imperdiet at, vulputate non felis. Aliquam sed libero vulputate, molestie nunc sollicitudin, 
      consequat libero. Curabitur tincidunt tortor in arcu efficitur, non bibendum justo aliquet. Morbi rhoncus diam eu ipsum
      consequat, sit amet lacinia purus cursus. Proin gravida sem semper metus suscipit egestas. In malesuada viverra molestie.
      Maecenas vehicula a augue et rutrum.
    </div>
    
    <div id="size">
      <select class="dropdown">
        <option value="default">Choose your size...</option>
        <option value="xs">X-Small</option>
        <option value="s">Small</option>
        <option value="m">Medium</option>
        <option value="l">Large</option>
        <option value="xl">X-Large</option>
      </select>
    </div>  
    
    <div id="color">
      <select class="dropdown">
        <option value="default">Choose a color...</option>
        <option value="red">Red</option>
        <option value="green">Green</option>
        <option value="purple">Purple</option>
        <option value="blue">Blue</option>
        <option value="yellow">Yellow</option>
        <option value="orange">Orange</option>
        <option value="white">White</option>
        <option value="black">Black</option>
      </select>
    </div>
    
    <div id="quantity">
      <input type="number" name="quantity" min="1" max="100" placeholder="Quantity" />
    </div>
    
    <div id="itemaddtocart">
      <!-- Color and Size have to be validated before added to cart? -->
      <h4><a href="#">Add to Cart</a></h4>
    </div>
  </div>

</div>

<div id="recommended">
 <h4>Recommended for you</h4>
  <p>Loop through a couple products in same subcategory</p>
</div>
</div>

<%= puts @param1 %>

<% end %>

app/views/products/show.html.erb
<% content_for :title do %>
Product Details
<% end %>

<% content_for :header do %>
<% end %>

<% content_for :content do %>
<div id="itemcont">
<div id="breadcrumbs">
  <ul>
    <li>
      <h4><%= link_to "Home", :action => 'home', :controller => :site %></h4>
    </li>
    <li>
      >
    </li>
    <li>
      <h4><%= link_to @product.Catagory.titlecase, :action => @product.Catagory, :controller => :products %></h4>
    </li>
    <li>
      >
    </li>
    <li>
      <h4><%= link_to @product.subcategory.titlecase, :action => 'subcategory', 
        :subcategory => @product.subcategory, :breadcrumbsCategory => @product.Catagory %>
      </h4>
    </li>
    <li>
      >
    </li>
  </ul>
</div>

<div id="item">

  <h2><%= @product.Title %></h2>
  
  <div id="itemimg">
    <%= image_tag @product.image_url %>
  </div>

  <%= form_for(@TempOrder) do |f| %>
  <div id="itemdesc">
    <h4 id="itemprice"><%= number_with_precision(@product.price, precision: 2) %></h4>
    <%= f.hidden_field :Total_Price ,:value => @product.price %>
    <%= f.hidden_field :OrderID ,:value => "0" %>
    <%= f.hidden_field :Product_id ,:value => @product.id %>
    
    <%puts "THIS IS AT PRODUCT VALUE" + @product.id.to_s %>
    
    <div id="rating">
      <div id="viewRating"></div>
      <ul id="review">
        <li>
          <h4><a id="review_trigger" href="#reviews">View Reviews</a></h4> 
        </li>
        <li>
          ||
        </li>
        <li>
          <h4><%= link_to "Review this Product", new_review_path(:productid => @product.id) %></h4>
        </li>
      </ul>
    </div>

    <div id="desc">
      <%= @product.Description %>
      <br/>
      <br/>
      <%= @product.features %>
<<<<<<< HEAD
<div>
        <%if @product.Size == 'all' %>
          <%= f.select(:Colour, [["Select Color",0],['xs',1],['s',2],['m',3],['l',4],['xl',5]]) %>
        <%elsif @product.Size == 'shoe' then %>
          <%= f.select :Colour, [["Select Color",0],['4',1],['5',2],['6',3],['7',4],['8',4]] %>
        <%else%>
          <%= f.select :Colour, [["Select Color",0],["One Size",1]] %>
=======
    </div>
      <div>
        <% if @product.Colour == 'all' %>
          <%= f.select :Colour, [["Select Color",0],['xs',1],['s',2],['m',3],['l',4],['xl',5]], :required => true  %>
        <% elsif @product.Size == 'shoe' then %>
          <%= f.select :Colour, [["Select Color",0],['4',1],['5',2],['6',3],['7',4],['8',4]], :required => true  %>
        <% else %>
          <%= f.select :Colour, [["Select Color",0],["One Size",1]], :required => true  %>
>>>>>>> f1bcae6919aef3067e8c48c87441cc37993bdc71
        <% end%>
        
    </div>
    <div>

        <% if @product.Size == 'all' %>
          <%= f.select :Size, [["Select Color",0],['xs',1],['s',2],['m',3],['l',4],['xl',5]], :required => true  %>
        <% elsif @product.Size == 'shoe' then %>
          <%= f.select :Size, [["Select Color",0],['4',1],['5',2],['6',3],['7',4],['8',4]], :required => true  %>
        <% else %>
          <%= f.select :Size, [["Select Color",0],["One Size",1]], :required => true %>
        <% end%>
        
    </div>

    <div id="quantity">
      <%= f.number_field :Quantity, :class => 'text_field', :step => 'any', :required => true  %>
      <%= puts "THIS IS THE VALUE FROM THE CONTROLLER " + calculatetotal().to_s  %>
    </div>
    
    <div id="itemaddtocart">
      <% if session[:username] %>
        <%= f.submit "Add to Cart", class: "btn btn-primary", :id => "itemaddtocartbtn" %>
      <% else %>
        <p class="centeralign">Please Login to add Items to Cart</p>
      <% end %>
    <%end%>
    </div>
  </div>

</div>

<div id="recommended">
 <h3 id="recommendedh3">Recommended for you</h3>
 <table id="productsTable">
    <col width="23%" />
    <col width="23%" />
    <col width="23%" />
    <col width="23%" />
 
 <% @recommended.each_with_index do |product, index| %>
  <% if index % 4 == 0 %>
   <tr>
  <% end %>
   <td>
    <div class="eachproduct">
     <%= link_to image_tag(product.image_url, :class => "productsimg"), product %>
     <h3 class="title"><%= link_to product.Title, product %></h3>
    </div>
   </td>
   <% if index % 4 == 3 %>
    </tr>
   <% end %>
 <% end %>
 </table>
</div>

<div id="reviews" style="display:none;">
	<header class="popupHeader" style="height: auto;">
		<div class="header_title">Reviews</div>
		<div class="modal_close">Close</div>
	</header>
	<section class="reviewshowBody">
		<div id="viewreviews">
			<% if @reviews.length != 0 %>
				<% @reviews.each_with_index do |review, index| %>
				  <% if index % 2 == 0 %>
				    <div id="reviewsWhite">
				  <% else %>
				    <div id="reviewsGrey">
				  <% end %>
          <%= render partial: "review", locals: {review: review, index: index} %>
          </div>
        <% end %>
			  <div id="writereview">
			    Write your own Review <%= link_to "here", new_review_path(:productid => @product.id), {:class => "link"} %>.
			  </div>
		  <% else %>
			  <div id="noreviews">
    			<p>
    			  This product hasn't been reviewed yet.
    			</p>
    			<p>
    				Be the first to review this product <%= link_to "Here", new_review_path(:productid => @product.id), {:class => "link"} %>!
    			</p>
  			</div>
			<% end %>
		</div>
	</section>
</div>
</div>
	<script type="text/javascript">
	  $("#review_trigger").leanModal({top : 100, overlay : 0.6, closeButton: ".modal_close" });
	  
	  $('#viewRating').raty({
      readOnly: true,
      hints: ['Abominable', 'Poor', 'Average', 'Good', 'Gorgeous'],
      score: <%= @product.rating %>,
      path: '/assets/products'
    });
	</script>
</div>

<% end %>

app/views/products/show.html3.erb
<% content_for :title do %>
Product Details
<% end %>

<% content_for :header do %>
<% end %>

<% content_for :content do %>
<div id="itemcont">
<div id="breadcrumbs">
  <ul>
    <li>
      <h4><%= link_to "Home", :action => 'home', :controller => :site %></h4>
    </li>
    <li>
      >
    </li>
    <li>
      <h4><%= link_to @product.Catagory.titlecase, :action => @product.Catagory, :controller => :products %></h4>
    </li>
    <li>
      >
    </li>
    <li>
      <h4><%= link_to @product.subcategory.titlecase, :action => 'subcategory', 
        :subcategory => @product.subcategory, :breadcrumbsCategory => @product.Catagory %>
      </h4>
    </li>
    <li>
      >
    </li>
  </ul>
</div>

<div id="item">

  <h2><%= @product.Title %></h2>
  
  <div id="itemimg">
    <%= image_tag @product.image_url %>
  </div>
<<<<<<< HEAD
=======
  

>>>>>>> 929ff14b9bebbe8a21bc3fc5f7f92ab473c0847a

   <%= form_for(@TempOrder) do |f| %>

  <div id="itemdesc">
<<<<<<< HEAD
    <h4 id="itemprice"><%= f.label :price,number_with_precision(@product.price, precision:2) %></h4>
=======
    <h4 id="itemprice"><%= number_with_precision(@product.price, precision: 2) %></h4>
    <%= f.hidden_field :Total_Price ,:value => @product.price %>
    <%= f.hidden_field :OrderID ,:value => "0" %>
    


>>>>>>> 929ff14b9bebbe8a21bc3fc5f7f92ab473c0847a
    <div id="rating">
      <div id="viewRating"></div>
      <ul id="review">
        <li>
          <h4><a id="review_trigger" href="#reviews">View Reviews</a></h4> 
        </li>
        <li>
          ||
        </li>
        <li>
          <h4><%= link_to "Review this Product", new_review_path(:productid => @product.id) %></h4>
        </li>
      </ul>
    </div>

    <div id="desc">
      <%= @product.Description %>
      <br/>
      <br/>
      <%= @product.features %>
    </div>
    
    <%puts "This is product size" + @product.Size.to_s %>

      <div>
        
        <%if @product.Size == 'all' %>
          <%= f.select(:Colour, [["Select Color",0],['xs',1],['s',2],['m',3],['l',4],['xl',5]]) %>
        <%elsif @product.Size == 'shoe' then %>
          <%= f.select :Colour, [["Select Color",0],['4',1],['5',2],['6',3],['7',4],['8',4]] %>
        <%else%>
          <%= f.select :Colour, [["Select Color",0],["One Size",1]] %>
        <% end%>
        
    </div>
    <div>

        <%if @product.Size == 'all' %>
          <%= f.select(:Size, [["Select Color",0],['xs',1],['s',2],['m',3],['l',4],['xl',5]]) %>
        <%elsif @product.Size == 'shoe' then %>
          <%= f.select :Size, [["Select Color",0],['4',1],['5',2],['6',3],['7',4],['8',4]] %>
        <%else%>
          <%= f.select :Size, [["Select Color",0],["One Size",1]] %>
        <% end%>
        
    </div>
        
 
    
    <div id="quantity">
      
      <%= f.number_field :Quantity, :class => 'text_field', :step => 'any' %>
      
      <%= puts "THIS IS THE VALUE FROM THE CONTROLLER " + calculatetotal().to_s  %>
      
      
      
    </div>
    
    
    <div id="itemaddtocart">
      <!-- Color and Size have to be validated before added to cart? -->
<<<<<<< HEAD
      <h4><%= link_to "Add to Cart", 'cart', :id => "itemaddtocart" %></h4>
      <%= tag "input", { "type" => "button", "value" => "Add to Cart", "onclick" => "addToCart(#{@product.price},#{@product.id})" } %>
      <%= tag "input", { "type" => "button", "value" => "List", "onclick" => "window.location.replace('../viewcart')" } %>
      <%= tag "input", { "type" => "button", "value" => "Clear Details(Will be removed)","onclick" => "cleardetails()" } %>
=======
      <h4><a href="#">Add to Cart</a></h4>
      <%= f.submit "Add todo", class: "btn btn-primary" %>
      <%end%>
>>>>>>> 929ff14b9bebbe8a21bc3fc5f7f92ab473c0847a
    </div>
  </div>

</div>

<div id="recommended">
 <h3 id="recommendedh3">Recommended for you</h3>
 <table id="productsTable">
    <col width="23%" />
    <col width="23%" />
    <col width="23%" />
    <col width="23%" />
 
 <% @recommended.each_with_index do |product, index| %>
  <% if index % 4 == 0 %>
   <tr>
  <% end %>
   <td>
    <div class="eachproduct">
      <%= render partial: "product", locals: {product: product, index: index} %>
    </div>
   </td>
   <% if index % 4 == 3 %>
    </tr>
   <% end %>
 <% end %>
 </table>
</div>

<div id="reviews" style="display:none;">
  <header class="popupHeader" style="height: auto;">
   <div class="header_title">Reviews</div>
   <div class="modal_close">Close</div>
  </header>
  <section class="reviewshowBody">
   <div id="viewreviews">
    <% if @reviews.length != 0 && @reviews != nil %>
      <% @reviews.each_with_index do |review, index| %>
        <% if index % 2 == 0 %>
          <div id="reviewsWhite">
        <% else %>
          <div id="reviewsGrey">
        <% end %>
            <%= render partial: "review", locals: {review: review, index: index} %>
            </div>
          <% end %>
      <div id="writereview">
        Write your own Review <%= link_to "here", new_review_path(:productid => @product.id), {:class => "link"} %>.
      </div>
      <% else %>
       <div id="noreviews">
         <p>
           This product hasn't been reviewed yet.
         </p>
         <p>
          Be the first to review this product <%= link_to "Here", new_review_path(:productid => @product.id), {:class => "link"} %>!
         </p>
       </div>
     <% end %>
    </div>
   </section>
</div>
</div>
 <script type="text/javascript">
   $("#review_trigger").leanModal({top : 100, overlay : 0.6, closeButton: ".modal_close" });
   
   $('#viewRating').raty({
      readOnly: true,
      hints: ['Abominable', 'Poor', 'Average', 'Good', 'Gorgeous'],
      score: <%= @product.rating %>,
      path: '/assets/products'
    });
 </script>
</div>

<% end %>