config/routes.rb
Rails.application.routes.draw do

  resources :products
  
  resources :cart, only:[:show]
  
  resources :contacts
  
  resources :users
  
  resources :order_items, only: [:create,:update,:destroy]
  
  resources :reviews

  get 'order_items/create'
  get 'aaa' => 'order_items#new'
  get 'order_items/update'
  get 'order_items/destroy'
  get 'createOrderItem' => 'products#createOrderItem'

  get 'womens' => 'products#women'
  get 'mens' => 'products#men'
  get 'sport' => 'products#sport'
  get 'subcategory' => 'products#subcategory'
  get 'priceRange' => 'products#priceRange'
  get 'search' => 'products#search'
  get 'products/index'
  
  get 'contact' => 'contacts#new'
  get 'contacts/new'
  
  get 'home' => 'site#home'
  get 'about' => 'site#about'

  get 'change_details' => 'users#change_details'
  get 'updateAccount' => 'users#updateAccount'
  get 'updateBilling' => 'users#updateBilling'
  get 'updateDelivery' => 'users#updateDelivery'
  get 'account' => 'users#show'
  
  get 'login'   => 'sessions#new'
  post 'login'   => 'sessions#create'
  get 'logout'  => 'sessions#destroy'
  get 'loginerror' => 'sessions#error'
  
  get 'cartcreate' => 'carts#create'
  get 'cart' => 'carts#index'
  get 'checkout' => 'carts#checkout'
  get 'submitOrder' => 'carts#submitOrder'
  get 'viewcart' => 'carts#view'
  
  get 'ordersignoff' => 'admin#ordersignoff'
  get 'viewmessages' => 'admin#viewmessages'
  get 'viewproducts' => 'admin#viewproducts'
  get 'editproduct' => 'admin#editproduct'
  
  
  root 'site#home'

end

app/views/layouts/_loginform.html.erb
<div id="modal" class="popupContainer" style="display:none;">
	<header class="popupHeader">
		<div class="header_title">Login</div>
		<div class="modal_close">Close</div>
	</header>
	<section class="popupBody">
		<!-- User Login -->
		<div class="user_login">
			<!-- WHY IS THIS LOGIN PATH? TO BE CHECKED FURTHER-->
			<%= form_for :session, url: login_path, html: {:class => "form"} do |f| %>
			
				<table>
				    <tr class="space">
				      <td>Username</td>
				      
				      <td><%= f.text_field :email, :autofocus=>true, :required => true, :placeholder => "(Your Email)"%></td>
				      
				    </tr>
				    <tr class="space">
				      <td>Password</td>
				      <td><%= f.password_field :password, :required => true %></td>
				    </tr>
				    <tr>
				    	<td></td>
				      <td style="text-align: right;"><%= f.submit "Submit", class: "btn btn-primary", id: "sendbtn" %></td>
				    </tr>
				</table>
			
			<%end%>
			
			<p>
				Don't have an account yet? <%= link_to "Sign up!", new_user_path, :class => "link" %>
			<br />
				<a href="#" class="link">Forgot your password?</a>
			</p>
		</div>
	</section>
</div>

app/views/layouts/application.html.erb
<% User_Var() %>

<!DOCTYPE html>
<html>
<head>
<title><%= yield(:title).empty? ? 'IN Fashion' : yield(:title) %></title>
<%= favicon_link_tag 'site/favicon.ico' %>
<meta charset="UTF-8">

<link href="https://fonts.googleapis.com/css?family=Lobster" rel="stylesheet" type="text/css">
<link href="https://fonts.googleapis.com/css?family=Cabin" rel="stylesheet" type="text/css">
<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
<%= csrf_meta_tags %>

</head>

<body>
	<header>
		<div id="logo">
			<img src="/assets/site/logo.png" alt="logo"/>
		</div>
		<div id="right">
			<% if session[:username].eql? "Admin" %>
				<div style="float: left; width: 100%;">Welcome <%= session[:username] %>; 
					You have <%= pluralize(10, "order") %> to Sign off on</div>
			<% elsif session[:username] != nil %>
				<div style="float: left; width: 93%;">Welcome, <%= session[:username] %>; Your Cart total is €</div>
				<div id="cp1" style="float: left; width: 7%; text-align: left;"><%= calculatetotal() %></div>
			<% else %>
				Welcome  to our online store!
			<% end %>
			<br/>
			<ul id="quicklinks">
				<li><%=link_to "My Account", "/account" %></li>
				<li> | </li>
				<% if session[:username].eql? "Admin" %>
					<li><%=link_to "Sign off on Orders", '/ordersignoff' %></li>
					<li> | </li>
					<li><%=link_to "View Messages", '/viewmessages' %></li>
					<li> | </li>
					<li><%=link_to "View Products", '/viewproducts' %></li>
				<% else %>
					<li><%=link_to "My Cart", '/cart' %></li>
					<li> | </li>
					<li><%=link_to "Checkout", '/checkout' %></li>
				<% end %>
				<li> | </li>
				<% if session[:username] != nil %>
					<%=link_to "Logout", '/logout' %>
				<%else%>
					<li><a id="modal_trigger" href="#modal">Login/Signup</a></li>
				<%end%>
			</ul>
		</div>
		<% if session[:username].eql? "Admin" %>
		<% else %>
		<div id="nav">
			<ul>
				<li><%=link_to "Women's", '/womens' %></li> 
				<li><%=link_to "Men's", '/mens' %></li> 
				<li><%=link_to "Sport's Wear", '/sport' %></li>
			</ul>
		</div>
		<% end %>
	</header>
	
	<div id="navimg">
		<%= yield :header %>
	</div>
	
	<div id="main">
		<%= yield :content %>
		<%= render partial: ("/layouts/loginform") %>
	</div>
	
	<script type="text/javascript">
		$("#modal_trigger").leanModal({top : 200, overlay : 0.6, closeButton: ".modal_close" });
	</script>

	<footer>
		<div id="footerlinks">
			<ul>
				<li><%=link_to "Home", '/home' %></li> 
				<li> | </li>
				<li><%=link_to "Women's", '/womens' %></li> 
				<li> | </li>
				<li><%=link_to "Men's", '/mens' %></li> 
				<li> | </li>
				<li><%=link_to "Sport Wear", '/sport' %></li>
				<li> | </li>
				<li><%=link_to "About", '/about' %></li> 
				<li> | </li>
				<li><%=link_to "Contact", new_contact_path %></li> 
			</ul>
		</div>
		
		<div id="updated">
			&copy; IN Fashion 2015
		</div>
	</footer>
	
</body>
</html>